-- OSC Button Controller Setup Helper
-- This helps you configure each button controller quickly
-- Run this on each button computer to set it up

print("=================================")
print("  Button Controller Setup")
print("=================================")
print("")
print("This will help you configure this button")
print("controller for the OSC system.")
print("")

-- Get the cell coordinate
print("What cell is this button? (e.g., B7, E5, M10)")
print("Enter cell: ")
local cell = read():upper()

-- Parse the cell
local col_letter = cell:match("^(%a+)")
local row_num = tonumber(cell:match("(%d+)$"))

if not col_letter or not row_num then
    print("ERROR: Invalid cell format!")
    print("Examples: B7, E5, M10, N11")
    return
end

-- Calculate signal
local col_index = string.byte(col_letter) - string.byte('A') + 1
local signal = tonumber(tostring(col_index) .. tostring(row_num))

print("")
print("Cell: " .. cell)
print("Signal: " .. signal)
print("")

-- Get redstone side
print("Which side is the button/relay on?")
print("Options: top, bottom, left, right, front, back")
print("Enter side: ")
local side = read():lower()

if side ~= "top" and side ~= "bottom" and side ~= "left" and 
   side ~= "right" and side ~= "front" and side ~= "back" then
    print("ERROR: Invalid side!")
    return
end

print("")
print("Which side is the wired modem on?")
print("Enter side: ")
local modem_side = read():lower()

-- Generate the script
local script = string.format([[-- Button Controller for %s (Signal %d)
-- Auto-generated by setup helper

local MY_SIGNAL = %d
local REDSTONE_SIDE = "%s"
local MODEM_SIDE = "%s"

print("Button %s (Signal %d) - Ready")

local modem = peripheral.find("modem") or peripheral.wrap(MODEM_SIDE)
if not modem then
    error("No modem found!")
end

if modem.isWireless() then
    error("Need WIRED modem, not wireless!")
end

while true do
    local event, side, channel, replyChannel, message, distance = os.pullEvent("modem_message")
    
    if type(message) == "table" and message.signal == MY_SIGNAL then
        if message.command == "activate" then
            rs.setOutput(REDSTONE_SIDE, true)
            print("[" .. os.date("%%H:%%M:%%S") .. "] ON")
        elseif message.command == "deactivate" then
            rs.setOutput(REDSTONE_SIDE, false)
            print("[" .. os.date("%%H:%%M:%%S") .. "] OFF")
        end
    end
end
]], cell, signal, signal, side, modem_side, cell, signal)

-- Save it
print("")
print("Saving to 'startup.lua'...")
local file = fs.open("startup.lua", "w")
file.write(script)
file.close()

print("Done!")
print("")
print("=================================")
print("Configuration Summary:")
print("=================================")
print("Cell: " .. cell)
print("Signal: " .. signal)
print("Button Side: " .. side)
print("Modem Side: " .. modem_side)
print("")
print("This computer will now run automatically")
print("on startup! Reboot to start.")
print("")
print("Label this computer? (y/n)")
local label_it = read():lower()

if label_it == "y" then
    os.setComputerLabel("OSC_" .. cell)
    print("Labeled as: OSC_" .. cell)
end

print("")
print("Setup complete! Reboot when ready.")
